export enum ONBOARDING_TIPS {
	COMPLETE_PROFILE = "COMPLETE_PROFILE",
	SHARE_ON_SOCIAL_MEDIA = "SHARE_ON_SOCIAL_MEDIA",
	ENGAGE_WITH_COMMUNITY = "ENGAGE_WITH_COMMUNITY",
	UPDATE_REGULARLY = "UPDATE_REGULARLY",
	FOLLOW_INTERESTING_CREATORS = "FOLLOW_INTERESTING_CREATORS",
	PARTICIPATE_IN_DISCUSSIONS = "PARTICIPATE_IN_DISCUSSIONS",
	ASK_FOR_FEEDBACK = "ASK_FOR_FEEDBACK",
	PROVIDE_VALUE = "PROVIDE_VALUE",
	SHOWCASE_EXPERIENCE = "SHOWCASE_EXPERIENCE",
	MAKE_ROADMAP_RICH = "MAKE_ROADMAP_RICH",
	USE_VISUALS = "USE_VISUALS",
	STAY_CONSISTENT = "STAY_CONSISTENT",
}
