import {
	FACEBOOK_ICON,
	INSTAGRAM_ICON,
	LINKEDIN_ICON,
	TWITTER_ICON,
	YOUTUBE_ICON,
} from "@public/icons/socialMedia";
import { SOCIAL_MEDIA_ENUM } from "../enum/socialMediaEnum";
import { ReactNode } from "react";

export const SOCIAL_MEDIA_ICONS: Record<string, ReactNode> = {
	[SOCIAL_MEDIA_ENUM.TWITTER]: TWITTER_ICON,
	[SOCIAL_MEDIA_ENUM.LINKEDIN]: LINKEDIN_ICON,
	[SOCIAL_MEDIA_ENUM.INSTAGRAM]: INSTAGRAM_ICON,
	[SOCIAL_MEDIA_ENUM.YOUTUBE]: YOUTUBE_ICON,
	[SOCIAL_MEDIA_ENUM.FACEBOOK]: FACEBOOK_ICON,
};
